### ISSUE TITLE
OTU count needed for project progress reporting

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#15]
We've been using "number of OTUs in synthesis" as a progress metric. For synthetic tree 4.0 it is recorded as 41029, for example. I'm not sure exactly how it's measured; I always thought it was the number of nodes in the synthetic tree that corresponded to OTUs in input trees.  But if you count those in the 4.1 tree with

    grep '"terminal"' annotations.json | wc

you get 61891. That seems awfully high, given that the input tree set is almost identical.

Possible reasons
 - propinquity maps forwarded OTT ids and treemachine didn't? I don't know
 - I'm wrong about how the number was measured in treemachine ?
 - treemachine didn't count OTUs that were ancestors of other OTUs, but these show up in the propinquity annotations?

Not sure.

So this issue is about:
 1. Any idea why such a big difference?
 2. Please add some metric of this sort, or a few of them, to the annotations, to help in preparing the progress metrics reports.

**Comment by jar398** [comment]
@mtholder @bredelings ^

**Comment by jar398** [comment]
@mtholder writes in gitter (answering number 1 above, number 2 remains):

The terminal annotation is intended to express the fact that "this study sort of covers the putatitve taxon that you are interested in, in the sense that the putative taxon was a terminal (or exemplified terminal) in this study). So if you want to know where this putative taxon goes in the tree of life, this study says something about that." But if you have only one primate in your tree (pg123@tree456), and it is Homo sapiens then pg123@tree456 will have a terminal annotation for all of the nodes from Homo sapiens back to the Primates.

After the exemplification step there are 41,226 tips in the taxonomy.

I got that from otc-count-leaves ../opentree5.0/exemplified_phylo/taxonomy.tre with a new version of the tree, in case you want to see the command.

**Comment by mtholder** [comment]
The number I reported shows up in one of the JSON files produced by running the synthesis pipeline.

    blob = json.load(open("exemplified_phylo/index.json"))
    blob["exemplified_phylo"]["num_leaves_in_exemplified_taxonomy"]

See also http://phylo.bio.ku.edu/ot/opentree5.0/exemplified_phylo/index.html

I'm happy to move it to another annotations file/location if you tell me where you want it to be.

**Comment by jar398** [comment]
It would be great if the number were available from the tree_of_life/about API method. Tree machine currently gets all of its tree metadata from annotated_supertree/annotations.json, so putting the number there would entail the least implementation and human coordination work on the treemachine side. I don't know if it's the right place, architecturally speaking. Thanks

**Comment by mtholder** [comment]
it is a hack, but done with https://github.com/mtholder/propinquity/commit/695a1372d19d15616b962d2981457ab6d0deab6e
