### ISSUE TITLE
Exemplification

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#16]
In http://files.opentreeoflife.org/synthesis/opentree5.0/output/exemplified_phylo/index.html I see a list of taxa that were exemplified, and I see the trees resulting from the exemplification mapping, but I don't see the mapping itself (id to id or list of ids), and I don't see documentation on how exemplification is done.  It would be interesting to examine this, and to ask if the mapping is stable across synthesis runs.

**Comment by mtholder** [comment]
scroll down on that page, and you'll find a table showing the trees and the OTT Ids in those trees that were exemplified.

Scroll further down and you'll find a table that shows the higher taxon and the examplars used to replace it.

The process is documented at https://github.com/mtholder/propinquity/blob/master/exemplified_phylo/README.md

which will be the target of the "details on the procedure" link if the mtholder/master branch is merged to OpenTreeOfLife/master

**Comment by jar398** [comment]
Ah, I didn't scroll down far enough.

Maybe what you said in your issue comment should be on the HTML page itself.

Is copying from the mtholder repo to the opentreeoflife repo something you expect me to do?  Not sure what the recipe should be.

**Comment by mtholder** [comment]
I just created PR for the 3 repos that have changes from mtholder forks (otc, peyotl, and propinquity). I'll close this, but reopen it if there is more to do.
