### ISSUE TITLE
It should be possible to put the opentree config someplace other than ~/.opentree

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#22]
There are many situations where global configuration files are not suitable.  Peyotl allows you to put the configuration file anywhere, and pass its location as a parameter (or environment variable); so should propinquity.

Maybe this is already possible, in which case there is a documentation problem.

**Comment by mtholder** [comment]
this is fixed. there is now a OTC_CONFIG env variable that can be used to specify a path to a config file that will be used.
