### ISSUE TITLE
id repeated as a tip in subproblems 

### ISSUE THREAD

**Issue by mtholder** [OpenTreeOfLife/propinquity#24]
I think that this is a bug in the makefile.
@kcranston is seeing a 

    terminate called after throwing an instance of 'otc::OTCError'
    what():  OTT Id 896444 occurs at multiple tips!

message from the  `otc-graft-solutions` step. grepping for the ID yields:

    $ grep -ri 896444 subproblem_solutions
    subproblem_solutions/ott401858.tre:((((ott458064,ott458073),ott896448),ott1085187),(((((((((((((ott1034611,ott3112175),ott1034618),(ott984234,ott1024619)),(ott358146,ott866243)),ott984231),(ott358148,ott984238)),((((ott145708,ott984232),ott145706),(ott984236,ott984241)),ott896444)),(((ott407989,ott984240),ott3112140),ott407988)),(((ott372033,ott1034613),ott5788860),ott145710)),ott5788861),(((((((((ott407976,ott408705),ott407977),ott62066),(ott1034608,ott1034617)),ott407987),ott259140),(ott259142,ott300602)),ott407983),((((((ott366825,ott759359),ott1034610),ott759356),ott866241),ott372038),((ott984230,ott1034615),ott1079994)))),ott1034614),(ott81494,ott1085184)))ott401858;
    subproblem_solutions/ott896444.tre:((ott39468,ott372028),ott933277)ott896444;
    subproblem_solutions/ott81506.tre:(ott896444,ott1034608)ott81506;
    subproblem_solutions/paths.txt:./subproblem_solutions/ott896444.tre
    subproblem_solutions/solution-ids.txt:ott896444.tre

But `ott401858` is not a leaf in any subproblem. I think that it is probably cruft from a previous run. But it should not be listed in `subproblem_solutions/solution-ids.txt` So the bug is probably in the creation of that file.

**markdown fixed.

**Comment by mtholder** [comment]
It looks like the cause is use of `ls *.tre` in `bin/run-subproblem-finder.sh` coupled with the failure to clear out the `subproblems/scratch` dir is causing cruft from previous runs to be included in the list of subproblems if you rebuild without a `make clean`. This did not affect v5 because the output dir was clean, but we need to fix how the subproblems  ids are put into the id file.

**Comment by mtholder** [comment]
I see where to fix this in otcetera. Simple fix, but I won't get to it for a bit...

**Comment by bredelings** [comment]
I added some corresponding propinquity changes and tested the fix.  It 
seems to fix the problem, so I merged the otcetera branch.

As a side effect, the subproblem ids are no longer sorted.  This could 
be fixed separately.

-BenRI
