### ISSUE TITLE
Unsupported node?

### ISSUE THREAD

**Issue by josephwb** [OpenTreeOfLife/propinquity#29]
I needed a taxonomy tree labelled like the synthetic tree, so ran synthesis with a source tree in agreement with taxonomy (i.e. should have no influence on synthesis). I was surprised that the "synthetic tree" was more resolved than it should be. Here is the configuration:
```
tax_tree: (((A,B,C,D),(E,F,G)),(I,J));
source:   (((A,C),(E,G)),I);
expected: (((A,B,C,D),(E,F,G)),(I,J));
realized: ((((A,C),B,D),(E,F,G)),(I,J));
```
That is, "clade" (A,C) is in the result but is, in my eyes, unsupported.

Specifically, I am making a synthetic tree for Aves (81461) using tree ot_889&tree3 as the sole input.

**Comment by josephwb** [comment]
Oh and I am using ott2.10draft11.

**Comment by mtholder** [comment]
writing up your example in https://github.com/mtholder/propinquity/commit/54f65bb5e59b8489f0febceb317a16e8a7aaf909 
gave you're expected tree. What are the real OTT Ids of the suspicious
 clade in your non-sanitized example (w/ ott_889) ?

**Comment by josephwb** [comment]
I don't really understand the question. The unsupported node has a label of "mrcaott1858ott5481".

**Comment by josephwb** [comment]
It seems I got the taxonomy tree wrong (expected more resolution than there is). It looks like this:
```
tax_tree: ((A,B,C,D,(E,F,G)),(I,J));
```
Still, I _think_ the issue remains:
```
tax_tree: ((A,B,C,D,(E,F,G)),(I,J));
source:   (((A,C),(E,G)),I);
expected: ((A,B,C,D,(E,F,G)),(I,J));
realized: (((A,C),B,D,(E,F,G)),(I,J));
```

**Comment by josephwb** [comment]
Actually, I think it makes sense.
