### ISSUE TITLE
SHAs for phylesystem and collection shards

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#30]
Maybe I missed something, but in output/ I don't see SHAs (or tags) for the commits of the phylesystem or collection repos that provided the inputs...

**Comment by mtholder** [comment]
http://files.opentreeoflife.org/synthesis/opentree7.0/output/phylo_snapshot/index.html

**Comment by jar398** [comment]
I was looking in the 'phylogenetic inputs' section because this information
pertain to the phylogenetic inputs. It did not occur to me to look in the
'processing' section because it is not about the processing of the
phylogenetic inputs. I wonder if the home page could be restructured just a
little?
