### ISSUE TITLE
Broken links in output/

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#31]
http://files.opentreeoflife.org/synthesis/opentree7.0/output/logs/log-of-assessments.txt
is broken, linked from
http://files.opentreeoflife.org/synthesis/opentree7.0/output/

(similarly for all the other logs)

**Comment by mtholder** [comment]
those files are produced when run locally. So I suspect that it has something to do with how the results are tar'ed and moved to the server.

**Comment by jar398** [comment]
If the tar step is error-prone, perhaps it should be provided by
propinquity itself, rather than left up to the unreliable user?
