### ISSUE TITLE
error in make clean

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/propinquity#32]
```
rm -f ./assessments/supertree_degree_distribution.txt ./assessments/taxonomy_degree_distribution.txt ./assessments/lost_taxa.txt ./assessments/summary.json ./assessments/log.txt
if test -d ./phylo_input ; then rmdir --ignore-fail-on-non-empty ./phylo_input ; fi
rmdir: illegal option -- -
usage: rmdir [-p] directory ...
make: *** [clean] Error 1
```

Turns out the `--ignore-fail-on-non-empty` option does not exist on OS X.

**Comment by mtholder** [comment]
I can tweak this later. `rmdir ./phylo_input  || true` should be a workaround if this is blocking you.

**Comment by kcranston** [comment]
Maybe I am missing something, but in the latest version of the Makefile, wouldn't the rmdir lines starting [at line 71](https://github.com/OpenTreeOfLife/propinquity/blob/master/Makefile#L71) be dangerous if the output directory was the propinquity directory - you would delete the subdirectories of the propinquity repo, along with their .gitignore files and READMEs?

**Comment by mtholder** [comment]
I think that it will have no effect if there are files in the dir that were not artifacts of the build. (those build artifacts will be deleted in the line above). So, if the dir is not empty it will not be removed.

**Comment by kcranston** [comment]
Right. Ok, sorry for the noise. BTW, the `rmdir ./phylo_input  || true` worked on OS X.

**Comment by kcranston** [comment]
I changed the Makefile in [this commit](https://github.com/mtholder/propinquity/commit/ee6929f358ab9f931487810115eb4ff790163bbd) to use your proposed workaround.
