### ISSUE TITLE
Request to change studyid + treeid strings

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/propinquity#4]
There are currently strings in the propinquity output that look like "pg_2608_tree6288". While technically correct, since they will be documented as being opaque, I would like to see them changed.

I will give my reasoning at length, if asked; it may not be what you think.

Minimal change: replace the _ separator (between study id and tree id) with any special character that's not an XML id (i.e. ncname) character. There are three special XML id characters, - . _

I would also avoid colon : 

In the conflict service, I use #.  That turns these things into proper relative URLs, with a fragment id that is an XML id inside the 'resource', exactly as the W3C intended.

Since these strings are supposed to be opaque (never parsed), another solution is to use generated numbers or random strings.  I am not requesting that, just saying it's an option that seems ok.

**Comment by bredelings** [comment]
This seems like a good idea.  I have other things higher on my priority 
list, such as letting the root_ott_id be a parameter to synthesis.  But 
feel free to ping me.

-BenRI

**Comment by bredelings** [comment]
Hmm... using a completely opaque string might be a good idea.
This would require users to read the study_id and tree_id from the entry 
in source_id_map, which is the right thing to do, I think.
Will think about it.

**Comment by mtholder** [comment]
I do not have strong objections to changing this behavior, but we'll need to make sure that @josephwb isn't relying on the current behavior. And it'll still might be tedious to make sure we fix everything that needs to be fixed. I think they are treated opaquely in almost places, so there is also a good chance that this will be an easy change. Still, it would be great (for me) to understand what the upside is.

I think some of these end up as filenames, so I'd like to avoid `#` because it will require escaping in the context of shell commands.

**Comment by josephwb** [comment]
Thanks for checking on me @mtholder :bowtie:. I don't think this would change anything for me.

**Comment by josephwb** [comment]
A note: these strings _are_ printed verbatim as the sorted list of inputs (i.e. reflecting priority) in the tree_of_life/about service.
So probably do not want something too obfuscated, right?

**Comment by josephwb** [comment]
To be more explicit, this is what is returned:
```
...
"supported_by" : {
    "pg_420_tree522" : "node208771",
    "taxonomy" : "2.9draft12"
  },
  "terminal" : {
    "pg_2573_tree5959" : "ott696271",
    "pg_2822_tree6569" : "ott696271"
  }
...
  "sourceToMetaMap" : {
    "pg_2573_tree5959" : {
      "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
      "tree_id" : "tree5959",
      "study_id" : "pg_2573"
    },
    "pg_2822_tree6569" : {
      "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
      "tree_id" : "tree6569",
      "study_id" : "pg_2822"
    },
    "pg_420_tree522" : {
      "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
      "tree_id" : "tree522",
      "study_id" : "pg_420"
    },
    "taxonomy" : {
      "name" : "ott",
      "version" : "2.9draft12"
    }
  }
```

**Comment by josephwb** [comment]
Erg. Above is the arguson, not the tree_of_life/about service, but you get the idea (i.e. both raw keys and the map are returned). Here is an example from "node_info":
```
curl -X POST http://localhost:7474/db/data/ext/graph/graphdb/node_info -H "content-tye:application/json" -d '{"node_id":"ott5839486"}'
{
  "unique_name" : "Galloanserae",
  "name" : "Galloanserae",
  "rank" : "no rank",
  "ott_id" : 5839486,
  "opentree4.1" : {
    "supported_by" : {
      "pg_420_tree522" : "node208771",
      "taxonomy" : "2.9draft12"
    },
    "source_id_map" : {
      "pg_2573_tree5959" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree5959",
        "study_id" : "pg_2573"
      },
      "pg_2822_tree6569" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree6569",
        "study_id" : "pg_2822"
      },
      "pg_420_tree522" : {
        "git_sha" : "c6ce2f9067e9c74ca7b1f770623bde9b6de8bd1f",
        "tree_id" : "tree522",
        "study_id" : "pg_420"
      },
      "taxonomy" : {
        "name" : "ott",
        "version" : "2.9draft12"
      }
    },
    "terminal" : {
      "pg_2573_tree5959" : "ott696271",
      "pg_2822_tree6569" : "ott696271"
    },
    "tip_descendants" : 695
  },
  "tax_source" : {
    "ncbi" : "1549675"
  },
  "ot_node_id" : "ott5839486"
}
```

**Comment by bredelings** [comment]
Hey Jonathan,

     I'd be interested in hearing your reasoning on this.

-BenRI

**Comment by jar398** [comment]
You might think it's because I think people should be able to parse these strings. Remember that _ is a valid character in a tree id, so if it's also used as a separator, the parsing rules would be very sensitive - especially if study ids can be anything other than prefix_nnn, and I think we should make as few assumptions about study ids as well.  If _ is allowed in tree ids the split rule is to split at the second _. If _ is allowed in study ids then there is no way to make it unambiguous.

But that's not why I want the change. Typical programmers almost always work by reverse engineering. They will not read the documentation that says that these are opaque strings and shouldn't be interpreted. They will see that these strings look like studyid_treeid and not realize that this is coincidental and they shouldn't depend on there being no _ in treeid. They could split at the last _, which could give incorrect results, or they could do string.split('_')[2], which could also give incorrect results. The failure would be hard to detect and hard to diagnose. It creates unnecessary frustration for users of the API.

We do not control the syntax of treeids. They are arbitrary ncnames (XML ids) that might come out of NeXML files we didn't prepare.

Making these be obviously opaque (e.g. based on a counter) would solve the problem by removing the temptation to parse them. That would be fine with me. Making them correctly parseable in an obvious way solves the problem if you are committed to putting such alluring information in the string.

**Comment by jar398** [comment]
Seeing no action on this issue, perhaps the right approach is for me to write a transducer that can be run on propinquity output before it gets read by tm-lite ?  I don't want to create work for people who are already too busy.

**Comment by kcranston** [comment]
I am happy to make this change, if we decide on a separator (noting Mark's comment about wanting these strings to play nice as filenames).

**Comment by kcranston** [comment]
Chose '@' for these reasons:
* treeid from valid NeXML will never contain '@' (because it is not a valid ncname character)
* can use '@' in filenames without escaping

There are a surprisingly small number of characters that satisfy both of these requirements.
