### ISSUE TITLE
pipeline error if monophyly test fails

### ISSUE THREAD

**Issue by kcranston** [OpenTreeOfLife/propinquity#43]
If `MONOPHYLY_TEST_CSV_FILE` is set and one of the tests fails, the pipeline barfs with the following error:

```
Traceback (most recent call last):
  File "./bin/run_assessments.py", line 158, in <module>
    elif ott_id in bt_dict:
NameError: name 'bt_dict' is not defined
ls: /Users/karen/Documents/opentree/synthesis/treeoflife/opentree10.1/assessments/summary.json: No such file or directory
make: *** [/Users/karen/Documents/opentree/synthesis/treeoflife/opentree10.1/assessments/summary.json] Error 1
```

The issue is that `bt_dict`is not defined when the code [reaches this line](https://github.com/OpenTreeOfLife/propinquity/blob/4207a90933d2931a1579c64b17cd44fd3a5ff0d0/bin/run_assessments.py#L158), which only happens when one of the tests fails.

**Comment by bredelings** [comment]
OK, this seems to be a result of
```
    if True:
        ltb = {'result': 'Skipped test - have not updated tests to deal with 2 layers of taxon filtering', 'data': []}
        btb = dict(ltb)
        ub = dict(ltb)
```

**Comment by bredelings** [comment]
Looks like problem may just be that figuring out which taxa are lost from `exemplified_phylo/regraft_cleaned_ott.tre`, instead of figuring out which taxa are lost from the taxonomy.  (i.e. taxa that are pruned because they aren't in an input tree aren just missing, not broken.)

**Comment by bredelings** [comment]
Part 1 done - generate correct lost_taxa.txt

**Comment by bredelings** [comment]
Fixed on mtholder branch.
