### ISSUE TITLE
Url update for custom synth download

### ISSUE THREAD

**Issue by snacktavish** [OpenTreeOfLife/propinquity#59]
"download_url": "http://localhost:1983/v3/tree_of_life/custom_built_tree/opentreeoflife_default_34905_tmp99nzghff.tar.gz"
    
    Not urgent, but would be handy for the demo if it showed the true url

**Comment by mtholder** [comment]
Now fixed. Notes at https://github.com/OpenTreeOfLife/ws_wrapper/issues/4
